name: master_thesis
channels:
  - anaconda
  - conda-forge

dependencies:
  - conda-forge::python=3.11.7
  - conda-forge::pip

  - pip:
      - torch
      - torchvision
      - tensorboard
      - matplotlib
      - scipy
      - opencv-python
      - pytorch-lightning

